### ISSUE TITLE
Web Marketing

### ISSUE THREAD

**Issue by WSMorrison** [WSMorrison/LegoThenMadeNow#13]
Create a web marketing plan and implement it.

- [ ]  Research web marking for similar small web businesses
- [ ]  Include social media marketing
  - [ ]  Facebook (possibly compulsory?)
  - [ ]  Instagram (link in progress LegoThenMadeNow)
- [ ]  Create email marketing
  - [ ]  Make sure this isn't obnoxiously intrusive, websites suck these days, do NOT use the modal that pops up just as the user is getting to interact with the page
  - [ ]  Investigate using a "Sign up and get a free instrustions!" first email, which would need coupon codes.
